### ISSUE TITLE
Cannot use import statements outside a module

### ISSUE THREAD

**Issue by gustavo-iha** [intlify/eslint-plugin-vue-i18n#159]
**My environment**

- **ESLint version: 6.8.0**
- **eslint-plugin-vue version: 6.2.2**
- **eslint-plugin-vue-i18n version: 0.10.0**
- **Node version: v14.15.4**

**My .eslintrc**

```js
module.exports = {
  parserOptions: {
    parser: 'babel-eslint'
  },
  extends: [
    'plugin:@intlify/vue-i18n/recommended'
  ],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'vue/attributes-order': 'error',
    'no-multi-str': 'off',
    "@intlify/vue-i18n/no-missing-keys-in-other-locales": 'off'
  },
  settings: {
    'vue-i18n': {
      localeDir: './src/langs/**/*.js'
    }
  },
  globals: {
    context: true
  },
  overrides: [
    {
      files: [
        '**/__tests__/*.{j,t}s?(x)',
        '**/tests/unit/**/*.spec.{j,t}s?(x)'
      ],
      env: {
        jest: true
      }
    }
  ]
}
```

When I run `vue-cli-service lint` it raises an error as if other linting rules had been added to my project. Full log below.

```
> vue-cli-service lint

 ERROR  SyntaxError: Cannot use import statement outside a module
Occurred while linting /var/app/src/components/TheFooter.vue:10
/var/app/src/langs/app/index.js:1
import validations from './validations'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at ResourceLoader.loader (/var/app/node_modules/@intlify/eslint-plugin-vue-i18n/dist/utils/locale-messages.js:92:24)
    at ResourceLoader.getResource (/var/app/node_modules/@intlify/eslint-plugin-vue-i18n/dist/utils/resource-loader.js:32:39)
    at FileLocaleMessage.getMessagesInternal (/var/app/node_modules/@intlify/eslint-plugin-vue-i18n/dist/utils/locale-messages.js:103:31)
    at FileLocaleMessage.get messages [as messages] (/var/app/node_modules/@intlify/eslint-plugin-vue-i18n/dist/utils/locale-messages.js:22:21)
    at FileLocaleMessage.getMessagesFromLocale (/var/app/node_modules/@intlify/eslint-plugin-vue-i18n/dist/utils/locale-messages.js:42:25)
    at /var/app/node_modules/@intlify/eslint-plugin-vue-i18n/dist/utils/locale-messages.js:134:58
    at Array.map (<anonymous>)
    at LocaleMessages.findMissingPath (/var/app/node_modules/@intlify/eslint-plugin-vue-i18n/dist/utils/locale-messages.js:134:45)
    at checkCallExpression (/var/app/node_modules/@intlify/eslint-plugin-vue-i18n/dist/rules/no-missing-keys.js:92:40)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! partners-up-frontend@0.1.0 lint: `vue-cli-service lint`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the partners-up-frontend@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-02-01T20_35_14_327Z-debug.log
```

I expected this rule not to be applied, nor any other, except for the i18n rules.

**Comment by gustavo-iha** [comment]
Never mind, I realized .js files are not compatible for now
